### NUMPY

##### To use numpy, we first need to install it and then import it in our files:
     import numpy as np (and now we are good to go and use the built in functions)

Creating an array using python lists

In [1]:
import numpy as np
list = [1,2,3,4,5]
#we use built in array function of numpy to create an array
my_arr = np.array(list)

print(my_arr)

[1 2 3 4 5]


Creating a 1-D array

In [2]:
arr = np.array([1,2,3,4,5])

print("1-D array:",arr)

1-D array: [1 2 3 4 5]


Creating a 2-D array

In [4]:
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Creating array with default value 0 

In [10]:
#default value will be zero, 3 is the shape that is the number of elements

#one dimensional
print("One dimensional array: ")
zero_arr = np.zeros(3)
print(zero_arr)

#two dimensional
print("Two dimensional array: ")
arr_zero = np.zeros((2,3))
print(arr_zero)

One dimensional array: 
[0. 0. 0.]
Two dimensional array: 
[[0. 0. 0.]
 [0. 0. 0.]]


Creating array with default value as 1

In [9]:
#creating one dimensional
print("One dimensional array: ")
arr1 = np.ones(4)
print(arr1)

#creating two dimensional
print("Two dimensional array: ")
arr2 = np.ones((2,3))
print(arr2)

One dimensional array: 
[1. 1. 1. 1.]
Two dimensional array: 
[[1. 1. 1.]
 [1. 1. 1.]]


Creating array with any custom default value

In [12]:
#custom value taken as 9
full_array = np.full((2,3),9)

print(full_array)

[[9 9 9]
 [9 9 9]]


Creating sequence of numbers in numpy

In [13]:
#use arange()

seq = np.arange(1,10,2)
print(seq)

[1 3 5 7 9]


Creating an identity matrix

In [16]:
#use eye function

new_arr = np.eye(3,3)
print(new_arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
