Indexing in NumPy arrays

Positive Indexing

In [4]:
import numpy as np

arr1 = np.array([10,20,30,40,50])
print(arr1[0]) #accessing the first element
print(arr1[2]) #accessing the third element
print(arr1[4]) #accessing last element

10
30
50


Negative Indexing

In [5]:
import numpy as np

arr2 = np.array([90,80,70,60])
print(arr2[-1]) #accessing last element
print(arr2[-4]) #accessing first element

60
90


Fancy Indexing

In [9]:
arr = np.array([10,20,30,40,50])
print(arr[[0,4,2]])

[10 50 30]


Slicing in NumPy Arrays

In [6]:
import numpy as np
arr3 = np.array([30,40,50,60,70])

print(arr3[1:4]) #prints 2&3 element 
print(arr3[:5]) #prints element from start to 4th pos
print(arr3[2:]) #prints element from 2nd pos to end
print(arr3[:]) #prints whole array
print(arr3[::2]) #prints whole array eliminating every 2nd element


[40 50 60]
[30 40 50 60 70]
[50 60 70]
[30 40 50 60 70]
[30 50 70]


Reversing the array

In [7]:
arr4 = np.array([10,30,50,70])

print(arr4[::-1])

[70 50 30 10]
