Boolean Masking/ Filtering

###### This helps in filtering the data through conditions

In [6]:
import numpy as np
arr = np.array([10,20,30,40,50])

#1. find elements which are greater than 30
mask = arr > 30
print(mask)

#2. use the mask to filter the values
print(arr[mask])

#3. direct filtering
print(arr[arr>30])

[False False False  True  True]
[40 50]
[40 50]


When there is more than 1 condition

In [9]:
arr = np.array([1,2,3,4,5])

#printing the values which is greater than 1 and less than 5 (1<val<5)

result = (arr > 1) & (arr < 5)
print(result)
print(arr[result])

#combining both the print statements into one/ one liner solution
print(arr[(arr>1)&(arr<5)])

[False  True  True  True False]
[2 3 4]
[2 3 4]


Modify: set all values to > 3  to 3

In [11]:
arr = np.array([1,2,3,4,5])

arr[arr > 3] = 3
print(arr)

[1 2 3 3 3]


Count how many values are above 10

In [15]:
arr1 = np.array([1,10,2,20,3,30,4,40,5,50])

count = np.sum(arr1 > 10)
print(count)

4


Get positions where value == 30

In [18]:
arr1 = np.array([1,10,2,20,30,30,4,40,5,50])

pos = np.where(arr1 == 30)
print(pos)

(array([4, 5]),)


Reshaping -> converting a 1D into 2D or NDarray

In [1]:
import numpy as np

arr1 = np.array([1,2,3,4,5,6])

print(arr1.reshape(2,3))

[[1 2 3]
 [4 5 6]]


Ravel -> converts 2D/ND array into 1D (makes a  view)

In [2]:
import numpy as np

# create a 2D array

arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2.ravel())

[1 2 3 4 5 6]


Flatten -> converts 2D/ND into 1D (makes a copy)

In [3]:
import numpy as np

#create a 2D array
arr_2d = np.array([[10,20,30],[40,50,60]])
print(arr_2d.flatten())

[10 20 30 40 50 60]
