Boolean Masking/ Filtering

###### This helps in filtering the data through conditions

In [1]:
import numpy as np
arr = np.array([10,20,30,40,50])

print(arr[arr>30])

[40 50]


Reshaping -> converting a 1D into 2D or NDarray

In [1]:
import numpy as np

arr1 = np.array([1,2,3,4,5,6])

print(arr1.reshape(2,3))

[[1 2 3]
 [4 5 6]]


Ravel -> converts 2D/ND array into 1D (makes a  view)

In [2]:
import numpy as np

# create a 2D array

arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2.ravel())

[1 2 3 4 5 6]


Flatten -> converts 2D/ND into 1D (makes a copy)

In [3]:
import numpy as np

#create a 2D array
arr_2d = np.array([[10,20,30],[40,50,60]])
print(arr_2d.flatten())

[10 20 30 40 50 60]
