#### Array Manipulation in NumPy

Inserting an element in 1D array

In [36]:
import numpy as np

arr1 = np.array([10,20,30])
print(arr1)

#we need to create a new array as arrays are of fixed length
#using insert func to add an elem
# syntax = np.insert(arr_name, pos, val, axis=None)

new_arr1 = np.insert(arr1, 0, 40, axis=None)
print(new_arr1)

[10 20 30]
[40 10 20 30]


Inserting an element in 2D array

1. When axis is 0 (Row)

In [37]:
import numpy as np

arr2d = np.array([[1,2],[3,4],[5,6]]) 
print(arr2d)

#creating a new array 
new_arr2d = np.insert(arr2d, 1, [7,8], axis=0) #axis=0 means, row will be inserted
print(new_arr2d)

[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [7 8]
 [3 4]
 [5 6]]


2. When axis is 1(Column)

In [38]:
import numpy as np
arr2d = np.array([[1,2],[3,4],[5,6]])
print(arr2d)

new_2darray = np.insert(arr2d, 1, [7,8,9], axis=1) #axis 1 means column
print(new_2darray)

[[1 2]
 [3 4]
 [5 6]]
[[1 7 2]
 [3 8 4]
 [5 9 6]]


Appending an element in 1D array

In [39]:
import numpy as np

arr1 = np.array([1,2,3,4,5,6])
arr2 = np.append(arr1, 7, axis=None)

print(arr1)
print(arr2)

[1 2 3 4 5 6]
[1 2 3 4 5 6 7]


Appending an element in a 2D array


1. When axis=1 :

In [40]:
import numpy as np

arr_2d = np.array([[1,2],[3,4]])
new_arr_2d = np.append(arr_2d, [[5],[7]], axis=1)
print(arr_2d)
print(new_arr_2d)

[[1 2]
 [3 4]]
[[1 2 5]
 [3 4 7]]


2. When axis=0:

In [41]:
import numpy as np

arr = np.array([[1,2],[3,4]])
print(arr)

new_arr = np.append(arr, [[5,6]], axis=0)
print(new_arr)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]


Concatenate 2 arrays (one dimensional)

In [42]:
import numpy as np

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr3 = np.concatenate((arr1,arr2), axis=0)
print(arr3)

[1 2 3 4 5 6]


Concatenate 2 arrays (2 Dimensional)

1. When axis=0

In [43]:
import numpy as np

arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])

arr3 = np.concatenate((arr1,arr2),axis=0)
print(arr3)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


2. When axis=1

In [44]:
import numpy as np

arr1 = np.array([[10,20],[30,40]])
arr2 = np.array([[50,60],[70,80]])

#concatenating 2 arrays at axis 1
arr3 = np.concatenate((arr1,arr2),axis=1)
print(arr3)

[[10 20 50 60]
 [30 40 70 80]]


Removing an element in 1D array

In [45]:
import numpy as np

arr = np.array([1,2,30,4,5,6])
updated_arr = np.delete(arr,2,axis=None)

print(updated_arr)


[1 2 4 5 6]


Removing an element in 2D array

1. When axis=0


In [46]:
import numpy as np

arr1 = np.array([[1,2,3],[40,50,60]])

new_arr = np.delete(arr1, 0, axis=0)
print(new_arr)

[[40 50 60]]


2. When axis=1

In [48]:
import numpy as np

arr2 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

updated_arr = np.delete(arr2, 1, axis=1)
print(updated_arr)

[[ 1  3]
 [ 4  6]
 [ 7  9]
 [10 12]]


Stacking in 1D array

1. vstack()

In [50]:
import numpy as np

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([7,8,9,10,11])

arr3 = np.vstack((arr1,arr2))
print(arr3)

[[ 1  2  3  4  5]
 [ 7  8  9 10 11]]


2. hstack()

In [51]:
import numpy as np

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr3 = np.hstack((arr1,arr2))
print(arr3)

[1 2 3 4 5 6]


Stacking in 2D array

1. vstack()

In [52]:
import numpy as np

arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])

#vertical stacking on 2d array

arr3 = np.vstack((arr1,arr2))
print(arr3)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


2. hstack()

In [53]:
import numpy as np

arr1 = np.array([[10,20],[30,40]])
arr2 = np.array([[50,60],[70,80]])

arr3 = np.hstack((arr1,arr2))
print(arr3)

[[10 20 50 60]
 [30 40 70 80]]
