#### Broadcasting in NumPy 

NumPy broadcasting is a mechanism that allows NumPy to perform arithmetic operations on arrays of different shapes and sizes

In [3]:
#Example of Broadcasting:
import numpy as np

#made an array of grocery price items
price_of_items = np.array([100,185,230,55,140])

#discount applied to each item is 10%
discount_applied = 10

#making a new array to store the final price of the items once the discount is applied:
final_price_check = price_of_items - (price_of_items* (discount_applied/100))
print(final_price_check)


[ 90.  166.5 207.   49.5 126. ]


How numpy handles calculations on different shapes and sizes

1. Matching Dimension

In [ ]:
import numpy as np

arr1 = np.array([10,20,30,40])
arr2 = np.array([50,60,70,80])

arr3 = arr1 + arr2
print(arr3)

#this basically adds the corresponding elements with each other

[ 60  80 100 120]


2. Expanding single elements

In [ ]:
arr = np.array([10,20,30,40,50])
elem = 3

#adds 3 in each element of arr array
new_arr = arr + elem
print(new_arr)

[13 23 33 43 53]


In [ ]:
arr_5_elem = np.array([10,20,30,40,50])
arr_3_elem  = np.array([90,80,70])

#adding 2 arrays of diff size
new_arr = arr_3_elem+arr_5_elem
print(new_arr) #this will give an error

Braodcasting from 1d to 2d

In [ ]:
import numpy as np

#creating a 2d array
arr_2d = np.array([[10,20,30],[40,50,60]])
arr_1d = np.array([1,2,3])

#add the two arrays
new_arr = arr_2d+arr_1d
print(new_arr)

#(matches the dimension - case1)

[[11 22 33]
 [41 52 63]]


Broadcasting from 1d to 2d (incompatible size/shape)

In [ ]:
import numpy as np

#two-dimeansional array
arr1 = np.array([[1,2,3],[4,5,6]])

#one-dimensional array
arr2 = np.array([10,20,30,40,50,60])

#adding the two arrays
total = arr1+arr2
# print(total)
#(if you will run this code then it will provide an error because of incompatible shapes)

#reshaping the arr2 
arr2 = np.reshape(arr2,(2,3))
print(arr2)

#adding the two arrays
total = arr1+arr2
print(total)


[[10 20 30]
 [40 50 60]]
[[11 22 33]
 [44 55 66]]
