#### Vectorisation

NumPy vectorization involves performing mathematical operations on entire arrays, eliminating the need to loop through individual elements.

Adding two arrays

In [18]:
import numpy as np

arr1 = np.array([10,20,30,40])
arr2 = np.array([50,60,70,80])

#printing the sum of 2 arrays-
print(arr1+arr2)

[ 60  80 100 120]


Multiplying array with a single element

In [19]:
import numpy as np

arr3 = np.array([1,2,3,4,5])
arr4 = arr3*2 #multiplies all the elements in arr3 with 2

print(arr4)

[ 2  4  6  8 10]


Dividing the whole array with single element

In [20]:
import numpy as np

arr5 = np.array([10,20,30])
arr6 = arr5/2 #divides all the elements of arr5 with 2

print(arr6)

[ 5. 10. 15.]


Subtracting the array using single element

In [21]:
import numpy as np

arr = np.array([1,2,3,4])
resluting_array = arr**2 #it will provide the square of elements in array

print(resluting_array)

[ 1  4  9 16]
