#### Practice Questions (Part-1)

Q1: Create a 1D array of even numbers from 10 to 50

Q2: Create a 5x3 array filled with number 7

Q3: Create an array of 20 random integers from 100–999 and reshape it into 4x5

Q4: How would you create a 3D array (2 blocks, each 3x3)?

In [11]:
import numpy as np

# creating 1d array of even numbers from 10-50
even_nums = np.arange(10,51,2)
print(even_nums)

# creating 5X3 array filled with 7
array_7 = np.full((5,3),7)
print(array_7)

# creating an array of 20 radom integers from 100-999 
rand_arr = np.random.randint(100,1000, size=20)

#reshaping it into 4X5
resized_arr = rand_arr.reshape(4,5)
print(resized_arr)

#creating a 3D array (2 blocks - 3X3)
arr_3d = np.random.randint(1,11, size=(2,3,3))
print(arr_3d)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]
[[7 7 7]
 [7 7 7]
 [7 7 7]
 [7 7 7]
 [7 7 7]]
[[420 569 870 564 169]
 [662 756 316 469 552]
 [100 564 347 120 412]
 [722 270 748 453 491]]
[[[6 3 5]
  [8 3 6]
  [7 3 7]]

 [[5 2 3]
  [9 6 7]
  [9 8 9]]]
