#### Practice Question (Part -2)

Q1: Extract the last row

Q2: Extract the last column

Q3: Get the middle 2x2 block from the modified array

Q4: Set the first row to all 0s

Q5: Create a 3D array of shape (2, 3, 4) and get:
- The second block
- The value at block 1, row 2, col 3

In [17]:
import numpy as np

arr = np.arange(1,13).reshape(3,4)
print(arr)

#extracting last row
last_row = arr[2]
print(last_row)

#extracting the last column
last_col = arr[:,3]
print(last_col)

#extracting the middle 2X2 block
block_arr = arr[1:, 1:3]
print(block_arr)

#setting first row to all zeros
arr[0,:] = 0
print(arr)

# creating a 3d array of shape(2,3,4)
arr_3d = np.arange(1,25).reshape(2,3,4)
print(arr_3d)

#extracting second block of 3d array
second_block = arr_3d[1,:,:]
print(second_block)

#extracting the value of block 1: row2 and col3
block_1 = arr_3d[0,1,2]
print(block_1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 9 10 11 12]
[ 4  8 12]
[[ 6  7]
 [10 11]]
[[ 0  0  0  0]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
7
