#### Practice Questions (Part-3)

Q1: Create a new 1D array of 15 random integers from 1 to 100

Q2: Print all even numbers from it

Q3: Replace all numbers < 50 with 0

Q4: Count how many numbers are now 0

Q5: Find the indexes of all values > 90

In [14]:
import numpy as np

#creating 1D array of random 15 integers
arr = np.random.randint(1,101,size=15)
print(arr)

#printing all even numbers
print(arr[arr % 2 == 0])

#replacing numbers less than 50 with 0
arr[arr < 50] = 0
print(arr)

#counting how many 0's are there in the modified array
print(np.sum(arr == 0))

#finding the indexes where value is > 90

indexes = np.where(arr > 90)
print(indexes)

[91 92 46 47 15 48 74 13 98 64 91 91 52 13  1]
[92 46 48 74 98 64 52]
[91 92  0  0  0  0 74  0 98 64 91 91 52  0  0]
7
(array([ 0,  1,  8, 10, 11]),)
