#### PRACTICE QUESTIONS (PART-4)

Q1: Create an array of 10 random floats from 1–100, rounded to 2 decimal places

Q2: Add 10 to every element

Q3: Replace all values > 90 with 90

Q4: Multiply every even index by 2 

Q5: Create a 2D array of shape (3, 4), add a 1D array of 4 elements to it using broadcasting

In [ ]:
import numpy as np

#q1 - creating an array from 1-100 of 10 random floats
float_arr = 99 * np.random.random_sample(size=10)  + 1
# print(float_arr)

#rounding the array's value upto 2
arr = np.round(float_arr,2)
print(arr)

#q2 - add 10 to every element
arr_add = arr + 10
print(arr_add)

#q3 - replace all values > 90 with 90
arr_add[arr_add > 90] = 90
print(arr_add)

#q4 - multiply every even index by 2
print(arr_add[::2]*2)

#q5 - creating a 2D array of shape (3,4)
arr_2d = np.arange(1,13).reshape(3,4)
print(arr_2d)

# creating 1D array of 4 elements
arr_1d = np.array([1,2,3,4])

#adding both arrays(broadcasting)
resulting_arr = arr_2d + arr_1d
print(resulting_arr)

[44.11 65.41 56.64 90.62 25.62 38.87 44.41  6.4  44.49 98.06]
[ 54.11  75.41  66.64 100.62  35.62  48.87  54.41  16.4   54.49 108.06]
[54.11 75.41 66.64 90.   35.62 48.87 54.41 16.4  54.49 90.  ]
[108.22 133.28  71.24 108.82 108.98]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 2  4  6  8]
 [ 6  8 10 12]
 [10 12 14 16]]
