#### PRACTICE QUESTIONS (PART-5)

Q1: Create a 4x4 array of random integers between 1–100

Q2: Calculate the mean of each row

Q3: Find the max of each column

Q4: Count how many values in total are > 50

Q5: What is the standard deviation of the entire array?

Q6: What is the median of each row?

In [9]:
import numpy as np

#creating a 4X4 array of random integers(1-100)
arr_2d = np.random.randint(1,101,size=16).reshape(4,4)
print("Original array:\n",arr_2d)

# calculating mean of each row
mean_row = np.mean(arr_2d,axis=1)
print("Row wise mean:",mean_row)

# finding maximum of each column
max = np.max(arr_2d, axis=0)
print("Maximum of each column:",max)

# counting how many values in total are >50
count = np.sum(arr_2d > 50)
print(count,"values in total are greater than 50")

# std deviation of the whole array
std_dev = np.std(arr_2d)
print("Standard Deviation:",std_dev)

# median of each row
median = np.median(arr_2d,axis=1)
print("Row wise median:",median)

Original array:
 [[65 30 39 18]
 [84 82 44  6]
 [90  9  1 80]
 [99 94 53  1]]
Row wise mean: [38.   54.   45.   61.75]
Maximum of each column: [99 94 53 80]
8 values in total are greater than 50
Standard Deviation: 34.68558553275409
Row wise median: [34.5 63.  44.5 73.5]
