#### SUDOKU VALIDATOR

**What's This Project About?**

You're given a completed 9×9 Sudoku board.

**Your task**: Check if it's a valid solution 

In [ ]:
import numpy as np

#hard-coding the sudoku value (9*9 - 2D)
board = np.array([[1,2,3,6,7,8,9,4,5],[1,8,4,2,3,9,7,6,1],[9,6,7,1,4,5,3,2,8],[3,7,2,4,6,1,5,8,9],[6,9,1,5,8,3,2,7,4],[4,5,8,7,9,2,6,1,3],[8,3,6,9,2,4,1,5,7],[2,1,9,8,5,7,4,3,6],[7,4,5,3,1,6,8,9,2]])
# print(board)

#looping through the rows for validation
for row in board:
    valid_row = np.unique(row)
    if np.array_equal(valid_row, np.arange(1, 10)):
        continue
    else:
        print(row)
        print("Invalid row")


#looping through the columns for validation
for col in range(9):
    column = board[:,col]
    valid_col = np.unique(column)
    if np.array_equal(valid_col, np.arange(1,10)):
        continue
    else:
        print(column)
        print("Invalid column")


#looping through rows and columns, all box(3*3)
for row in [0,3,6]:
    
    for col in [0,3,6]:
        
        box = board[row:row+3,col:col+3]
        # print(box)
        box_1d = box.flatten() #converting the 2D box into 1d
        final_box = np.unique(box_1d) #converting the 1d into ordered array [ 1 2 3 4 5 6 7 8 9]
        if np.array_equal(final_box,np.arange(1,10)): #checking if the box = [1 2 3 4 5 6 7 8 9]
            count = 0
            continue
        else:
            print(box)
            print("This box contains an error.") 
            break

print("Thanks for playing!🚀💗")


[1 8 4 2 3 9 7 6 1]
Invalid row
[1 1 9 3 6 4 8 2 7]
Invalid column
[[1 2 3]
 [1 8 4]
 [9 6 7]]
This box contains an error.
Thanks for playing!🚀💗
